### PR TITLE
fix multiple bugs with iis_vdir iis_root iis_app for idempotency

### LINKED ISSUE #374: iis_vdir not idempotent when using config action
### Cookbook version
6.5.3

### Chef-client version
13.1.31

### Platform Details
Windows Server 2012 R2 on Azure

### Scenario:
The iis_vdir resource isn't idempotent with the config action.

### Steps to Reproduce:
```
  # create site
  iis_vdir "#{virtual_site_name}/" do
    path virtual_attributes['path']
    physical_path virtual_physical_path.tr('/', '\\')
    action [:add, :config]
  end

```
### Expected Result:
No changes after the vdir is added.

### Actual Result:
This occurs on each run:

```
  * iis_vdir[www.drivermanagement.com/] action add[2017-06-01T16:33:16-05:00] INFO: Processing iis_vdir[www.drivermanage
ment.com/] action add (jjk_ts_transport_webserver_website_drivermanagement::default line 257)
[2017-06-01T16:33:16-05:00] WARN: application name: www.drivermanagement.com/
[2017-06-01T16:33:16-05:00] WARN: application name chomp: www.drivermanagement.com
 (up to date)
  * iis_vdir[www.drivermanagement.com/] action config[2017-06-01T16:33:16-05:00] INFO: Processing iis_vdir[www.driverman
agement.com/] action config (jjk_ts_transport_webserver_website_drivermanagement::default line 257)
[2017-06-01T16:33:16-05:00] WARN: application name: www.drivermanagement.com/
[2017-06-01T16:33:16-05:00] WARN: application name chomp: www.drivermanagement.com

    - Configured the VDIR - "iis_vdir[www.drivermanagement.com/]"
```

### PR DESCRIPTION
**Pull request by EasyAsABC123**
Signed-off-by: Justin Schuhmann <jmschu02@gmail.com>

### Description

- idempotency issue with `iis_app`
- idempotency issue with `iis_root`
- idempotency issue with `iis_vdir`

### Issues Resolved

#374 

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

File: libraries/helper.rb [hunk 1]
```diff
@@ -74,9 +74,9 @@ def windows_cleanpath(path)
       end
 
       def application_cleanname(application_name)
-        if !application_name.include?('/') && !application_name.end_with?('/')
+        if application_name.count('/') == 0
```
Comment (EasyAsABC123) [inline libraries/helper.rb]: same as previous but is more clear, if the item doesn't include a '/' and doesn't end in one (weird statement since if it doesn't contain one it likely doesn't end in one....
return the string with a '/' on the end.

File: libraries/helper.rb [hunk 2]
```diff
@@ -74,9 +74,9 @@ def windows_cleanpath(path)
...
           "#{application_name}/"
-        elsif application_name.chomp('/').include?('/') && application_name.end_with?('/')
+        elsif application_name.count('/') > 1
```
Comment (EasyAsABC123) [inline libraries/helper.rb]: same as previous, if the name with the last / removed still includes a / and the name ends in a / then remove the last /

Default Web Site/my app/ => Default Web Site/my app

File: resources/app.rb [hunk 3]
```diff
@@ -32,6 +32,8 @@
 
 load_current_value do |desired|
   site_name desired.site_name
+  # Sanitize physical path
+  desired.physical_path = windows_cleanpath(desired.physical_path)
```
Comment (EasyAsABC123) [inline resources/app.rb]: clean the path of the given physical path while loading values.

File: resources/app.rb [hunk 4]
```diff
@@ -49,7 +51,7 @@
         path value doc.root, 'APP/application/@path'
         application_pool value doc.root, 'APP/application/@applicationPool'
         enabled_protocols value doc.root, 'APP/application/@enabledProtocols'
-        physical_path value doc.root, 'APP/application/virtualDirectory/@physicalPath'
+        physical_path windows_cleanpath(value(doc.root, 'APP/application/virtualDirectory/@physicalPath'))
```
Comment (EasyAsABC123) [inline resources/app.rb]: clean the path of the discovered physical path

File: resources/app.rb [hunk 5]
```diff
@@ -60,55 +62,61 @@
 end
 
 action :add do
-  if current_resource.path.empty?
```
Comment (EasyAsABC123) [inline resources/app.rb]: no need to use this anymore, created function that contains this as `exists`

File: resources/app.rb [hunk 6]
```diff
@@ -60,55 +62,61 @@
...
+  if exists
```
Comment (EasyAsABC123) [inline resources/app.rb]: reversed to be positive statement

File: resources/app.rb [hunk 7]
```diff
@@ -60,55 +62,61 @@
...
+    Chef::Log.debug("#{new_resource.inspect} app already exists - nothing to do")
+  else
     converge_by "Creating the Application - \"#{new_resource}\"" do
       cmd = "#{appcmd(node)} add app /site.name:\"#{new_resource.site_name}\""
       cmd << " /path:\"#{new_resource.path}\""
       cmd << " /applicationPool:\"#{new_resource.application_pool}\"" if new_resource.application_pool
-      cmd << " /physicalPath:\"#{windows_cleanpath(new_resource.physical_path)}\"" if new_resource.physical_path
```
Comment (EasyAsABC123) [inline resources/app.rb]: no need to clean this since we clean it at the `load_current_values` now

File: resources/app.rb [hunk 8]
```diff
@@ -60,55 +62,61 @@
...
-  converge_if_changed :application_pool do
-    # adds applicationPool to the cmd
-    cmd << " /applicationPool:\"#{new_resource.application_pool}\"" if new_resource.application_pool
-  end
-  converge_if_changed :enabled_protocols do
-    # adds enabledProtocols to the cmd
-    cmd << " /enabledProtocols:\"#{new_resource.enabled_protocols}\"" if new_resource.enabled_protocols
-  end
-  Chef::Log.debug(cmd)
+  if exists
```
Comment (EasyAsABC123) [inline resources/app.rb]: only `config` if it exists

File: resources/app.rb [hunk 9]
```diff
@@ -60,55 +62,61 @@
...
 
-  if cmd == cmd_set_app
-    Chef::Log.debug("#{new_resource.inspect} application - nothing to do")
-  else
-    shell_out!(cmd)
-  end
+    if cmd == cmd_set_app
+      Chef::Log.debug("#{new_resource.inspect} application - nothing to do")
+    else
+      converge_by "Updating the Application - \"#{new_resource}\"" do
```
Comment (EasyAsABC123) [inline resources/app.rb]: Just a friendly message wrapper, and will keep the command from executing (which it shouldn't anyways since all above commands are wrapped with `converge_if_changed`

File: resources/app.rb [hunk 10]
```diff
@@ -60,55 +62,61 @@
...
+      Chef::Log.debug(cmd)
+      shell_out!(cmd)
+    end
+  else
+    Chef::Log.debug("#{new_resource.inspect} app needs to be added - cannot configure non-existent items")
   end
 end
 
 action :delete do
-  if !current_resource.path.empty?
```
Comment (EasyAsABC123) [inline resources/app.rb]: changed to `exists` function allowing us to change what "exists" means

File: resources/app.rb [hunk 11]
```diff
@@ -119,6 +127,10 @@
 end
 
 action_class.class_eval do
+  def exists
```
Comment (EasyAsABC123) [inline resources/app.rb]: declare to `exists` function allowing us to change what "exists" means

File: resources/module.rb [hunk 12]
```diff
@@ -60,7 +62,9 @@
 # appcmd syntax for adding modules
 # appcmd add module /name:string /type:string /preCondition:string
 action :add do
-  if !current_resource.type
```
Comment (EasyAsABC123) [inline resources/module.rb]: changed to exists

File: resources/module.rb [hunk 13]
```diff
@@ -60,7 +62,9 @@
...
+  if exists
```
Comment (EasyAsABC123) [inline resources/module.rb]: changed to postive

File: resources/module.rb [hunk 14]
```diff
@@ -34,6 +34,8 @@
 load_current_value do |desired|
   module_name desired.module_name
   application desired.application if desired.application
+  # Sanitize Image Path (file system path)
+  desired.image = windows_cleanpath(desired.image) if desired.image
```
Comment (EasyAsABC123) [inline resources/module.rb]: clean windows file path in `load_current_value`

File: resources/module.rb [hunk 15]
```diff
@@ -71,13 +75,11 @@
       shell_out!(cmd, returns: [0, 42])
       override_mode(node, current_resource.previous_lock, 'system.webServer/modules', new_resource.application)
     end
-  else
-    Chef::Log.debug("#{new_resource} module already exists - nothing to do")
   end
 end
 
 action :delete do
-  if current_resource.type
```
Comment (EasyAsABC123) [inline resources/module.rb]: changed to `exists`

File: resources/module.rb [hunk 16]
```diff
@@ -94,7 +96,9 @@
 # appcmd syntax for installing native modules
 # appcmd install module /name:string /add:string(true|false) /image:string
 action :install do
-  if !current_resource.type
+  if exists
```
Comment (EasyAsABC123) [inline resources/module.rb]: changed to `exists` and made postive

File: resources/module.rb [hunk 17]
```diff
@@ -105,15 +109,13 @@
...
     end
-  else
-    Chef::Log.debug("#{new_resource} module already exists - nothing to do")
   end
 end
 
 # appcmd syntax for uninstalling native modules
 # appcmd uninstall module <name>
 action :uninstall do
-  if current_resource.type
```
Comment (EasyAsABC123) [inline resources/module.rb]: changed to `exists`

File: resources/module.rb [hunk 18]
```diff
@@ -125,3 +127,9 @@
     Chef::Log.debug("#{new_resource} module does not exists - nothing to do")
   end
 end
+
+action_class.class_eval do
+  def exists
```
Comment (EasyAsABC123) [inline resources/module.rb]: created `exists` function to allow us to change what it means

File: resources/pool.rb [hunk 19]
```diff
@@ -173,7 +173,9 @@
 end
 
 action :add do
-  if !current_resource.runtime_version
+  if exists
```
Comment (EasyAsABC123) [inline resources/pool.rb]: created exists function to allow us to change what it means

File: resources/pool.rb [hunk 20]
```diff
@@ -237,14 +237,18 @@
...
-  if current_resource.runtime_version
+  if exists
     converge_by "Recycled Application Pool \"#{new_resource}\"" do
       shell_out!("#{appcmd(node)} recycle APPPOOL \"#{new_resource.name}\"") if current_resource.running
     end
   end
 end
 
 action_class.class_eval do
+  def exists
```
Comment (EasyAsABC123) [inline resources/pool.rb]: created `exists` function to allow us to change what it means

File: resources/site.rb [hunk 21]
```diff
@@ -167,60 +170,66 @@
 end
 
 action_class.class_eval do
+  def exists
```
Comment (EasyAsABC123) [inline resources/site.rb]: created `exists` function to allow us to change what it means

File: resources/vdir.rb [hunk 22]
```diff
@@ -126,6 +130,10 @@
 end
 
 action_class.class_eval do
+  def exists
```
Comment (EasyAsABC123) [inline resources/vdir.rb]: created `exists` function to allow us to change what it means

File: resources/site.rb [hunk 23]
```diff
@@ -41,6 +41,9 @@
 
 load_current_value do |desired|
   site_name desired.site_name
+  # Sanitize windows file system path
+  desired.path = windows_cleanpath(desired.path)
```
Comment (EasyAsABC123) [inline resources/site.rb]: clean windows file path in `load_current_value`

File: resources/site.rb [hunk 24]
```diff
@@ -41,6 +41,9 @@
...
+  desired.log_directory = windows_cleanpath(desired.log_directory)
```
Comment (EasyAsABC123) [inline resources/site.rb]: clean windows file path in `load_current_value`

File: resources/site.rb [hunk 25]
```diff
@@ -66,8 +69,8 @@
       if cmd.stderr.empty?
         xml = cmd.stdout
         doc = Document.new(xml)
-        path value doc.root, 'SITE/site/application/virtualDirectory/@physicalPath'
-        log_directory value doc.root, 'SITE/site/logFile/@directory'
+        path windows_cleanpath(value(doc.root, 'SITE/site/application/virtualDirectory/@physicalPath'))
```
Comment (EasyAsABC123) [inline resources/site.rb]: clean windows file path in `load_current_value`

File: resources/site.rb [hunk 26]
```diff
@@ -66,8 +69,8 @@
...
+        log_directory windows_cleanpath(value(doc.root, 'SITE/site/logFile/@directory'))
```
Comment (EasyAsABC123) [inline resources/site.rb]: clean windows file path in `load_current_value`

File: resources/site.rb [hunk 27]
```diff
@@ -93,11 +96,13 @@
...
 
 action :add do
-  if !current_resource.site_id
+  if exists
+    Chef::Log.debug("#{new_resource} site already exists - nothing to do")
+  else
     converge_by "Created the Site - \"#{new_resource}\"" do
       cmd = "#{appcmd(node)} add site /name:\"#{new_resource.site_name}\""
       cmd << " /id:#{new_resource.site_id}" if new_resource.site_id
-      cmd << " /physicalPath:\"#{windows_cleanpath(new_resource.path)}\"" if new_resource.path
```
Comment (EasyAsABC123) [inline resources/site.rb]: no need to clean path now since it happens in `load_current_values`

File: resources/pool.rb [hunk 28]
```diff
@@ -187,17 +189,15 @@
...
       configure
     end
-  else
-    Chef::Log.debug("#{new_resource} pool already exists - nothing to do")
   end
 end
 
 action :config do
-  configure if current_resource.runtime_version
+  configure if exists
```
Comment (EasyAsABC123) [inline resources/pool.rb]: `configure` if it `exists`

File: resources/pool.rb [hunk 29]
```diff
@@ -187,17 +189,15 @@
...
 end
 
 action :delete do
-  if current_resource.runtime_version
+  if exists
```
Comment (EasyAsABC123) [inline resources/pool.rb]: updated to new `exists` function so that it is easier to update all at once

File: resources/pool.rb [hunk 30]
```diff
@@ -207,7 +207,7 @@
 end
 
 action :start do
-  if current_resource.runtime_version && !current_resource.running
+  if exists && !current_resource.running
```
Comment (EasyAsABC123) [inline resources/pool.rb]: updated to new `exists` function so that it is easier to update all at once

File: resources/pool.rb [hunk 31]
```diff
@@ -217,7 +217,7 @@
 end
 
 action :stop do
-  if current_resource.runtime_version && current_resource.running
+  if exists && current_resource.running
```
Comment (EasyAsABC123) [inline resources/pool.rb]: updated to new `exists` function so that it is easier to update all at once

File: resources/pool.rb [hunk 32]
```diff
@@ -227,7 +227,7 @@
 end
 
 action :restart do
-  if current_resource.runtime_version
+  if exists
```
Comment (EasyAsABC123) [inline resources/pool.rb]: updated to new `exists` function so that it is easier to update all at once

File: resources/pool.rb [hunk 33]
```diff
@@ -237,14 +237,18 @@
 end
 
 action :recycle do
-  if current_resource.runtime_version
+  if exists
```
Comment (EasyAsABC123) [inline resources/pool.rb]: updated to new `exists` function so that it is easier to update all at once

File: resources/site.rb [hunk 34]
```diff
@@ -93,11 +96,13 @@
 end
 
 action :add do
-  if !current_resource.site_id
+  if exists
```
Comment (EasyAsABC123) [inline resources/site.rb]: updated to new `exists` function so that it is easier to update all at once and positive if condition

File: resources/site.rb [hunk 35]
```diff
@@ -117,17 +122,15 @@
...
       Chef::Log.info("#{new_resource} added new site '#{new_resource.site_name}'")
     end
-  else
-    Chef::Log.debug("#{new_resource} site already exists - nothing to do")
   end
 end
 
 action :config do
-  configure
+  configure if exists
```
Comment (EasyAsABC123) [inline resources/site.rb]: updated to new `exists` function so that it is easier to update all at once

File: resources/site.rb [hunk 36]
```diff
@@ -117,17 +122,15 @@
...
 end
 
 action :delete do
-  if current_resource.site_id
+  if exists
```
Comment (EasyAsABC123) [inline resources/site.rb]: updated to new `exists` function so that it is easier to update all at once

File: resources/site.rb [hunk 37]
```diff
@@ -138,7 +141,7 @@
 end
 
 action :start do
-  if !current_resource.running
+  if exists && !current_resource.running
```
Comment (EasyAsABC123) [inline resources/site.rb]: updated to new `exists` function so that it is easier to update all at once

File: resources/site.rb [hunk 38]
```diff
@@ -148,7 +151,7 @@
 end
 
 action :stop do
-  if current_resource.running
+  if exists && current_resource.running
```
Comment (EasyAsABC123) [inline resources/site.rb]: updated to new `exists` function so that it is easier to update all at once

File: resources/app.rb [hunk 39]
```diff
@@ -60,55 +62,61 @@
...
+      Chef::Log.debug("#{new_resource.inspect} application - nothing to do")
+    else
+      converge_by "Updating the Application - \"#{new_resource}\"" do
+        shell_out!(cmd)
+      end
+    end
 
-  converge_if_changed :physical_path do
-    cmd = "#{appcmd(node)} set vdir /vdir.name:\"#{vdir_identifier}\""
-    cmd << " /physicalPath:\"#{windows_cleanpath(new_resource.physical_path)}\""
```
Comment (EasyAsABC123) [inline resources/app.rb]: no need to clean this since we clean it at the `load_current_values` now

File: resources/site.rb [hunk 40]
```diff
@@ -167,60 +170,66 @@
...
-      end
+    converge_if_changed :application_pool do
+      cmd = "#{appcmd(node)} set app \"#{new_resource.site_name}/\" /applicationPool:\"#{new_resource.application_pool}\""
+      Chef::Log.debug(cmd)
+      shell_out!(cmd, returns: [0, 42])
+    end
 
-      if new_resource.path
-        cmd = "#{appcmd(node)} set vdir \"#{new_resource.site_name}/\""
-        cmd << " /physicalPath:\"#{windows_cleanpath(new_resource.path)}\""
```
Comment (EasyAsABC123) [inline resources/site.rb]: no need to clean path since clean windows file path in `load_current_value`

File: resources/site.rb [hunk 41]
```diff
@@ -167,60 +170,66 @@
...
+    converge_if_changed :site_id do
+      cmd = "#{appcmd(node)} set site \"#{new_resource.site_name}\""
+      cmd << " /id:#{new_resource.site_id}"
+      Chef::Log.debug(cmd)
+      shell_out!(cmd)
+    end
 
-      if new_resource.log_directory
-        cmd = "#{appcmd(node)} set site \"#{new_resource.site_name}\""
-        cmd << " /logFile.directory:#{windows_cleanpath(new_resource.log_directory)}"
```
Comment (EasyAsABC123) [inline resources/site.rb]: no need to clean path since clean windows file path in `load_current_value`

File: resources/vdir.rb [hunk 42]
```diff
@@ -34,10 +34,12 @@
 default_action :add
 
 load_current_value do |desired|
-  application_name application_cleanname(desired.application_name).end_with?('/') ? application_cleanname(desired.application_name) : application_cleanname(desired.application_name) + '/'
+  # Sanitize Application Name
+  desired.application_name = application_cleanname(desired.application_name)
+  # Sanitize Physical Path
+  desired.physical_path = windows_cleanpath(desired.physical_path)
```
Comment (EasyAsABC123) [inline resources/vdir.rb]: clean windows file path in `load_current_value`

File: resources/vdir.rb [hunk 43]
```diff
@@ -63,11 +65,13 @@
...
 
 action :add do
-  if !@current_resource.physical_path
+  if exists
+    Chef::Log.debug("#{new_resource} virtual directory already exists - nothing to do")
+  else
     converge_by "Created the VDIR - \"#{new_resource}\"" do
       cmd = "#{appcmd(node)} add vdir /app.name:\"#{vdir_identifier}\""
       cmd << " /path:\"#{new_resource.path}\""
-      cmd << " /physicalPath:\"#{windows_cleanpath(new_resource.physical_path)}\""
```
Comment (EasyAsABC123) [inline resources/vdir.rb]: no need to clean windows path since we clean windows file path in `load_current_value`

File: resources/vdir.rb [hunk 44]
```diff
@@ -77,45 +81,45 @@
...
-    Chef::Log.debug("#{new_resource} virtual directory already exists - nothing to do")
   end
 end
 
 action :config do
-  if current_resource.physical_path
-    converge_by "Configured the VDIR - \"#{new_resource}\"" do
-      cmd = "#{appcmd(node)} set vdir \"#{application_identifier}\""
-      converge_if_changed :physical_path do
-        cmd << " /physicalPath:\"#{windows_cleanpath(new_resource.physical_path)}\""
```
Comment (EasyAsABC123) [inline resources/vdir.rb]: no need to clean windows path since we clean windows file path in `load_current_value`

File: resources/root.rb [hunk 45]
```diff
@@ -54,41 +54,35 @@
...
-    end
-
-    converge_if_changed :default_documents do
-      set_default_documents(new_resource.default_documents, current_resource.default_documents)
-    end
-
-    converge_if_changed :mime_maps do
-      set_mime_maps(new_resource.mime_maps, current_resource.mime_maps)
-    end
+  converge_if_changed :default_documents_enabled do
```
Comment (EasyAsABC123) [inline resources/root.rb]: removed `converge_by` since it doesn't do anything in this use case

File: resources/root.rb [hunk 46]
```diff
@@ -54,41 +54,35 @@
...
 action :add do
-  converge_by "Added Root Config \"#{new_resource}\"" do
-    converge_if_changed :add_default_documents do
-      set_default_documents(new_resource.add_default_documents, current_resource.add_default_documents, true, false)
-    end
-
-    converge_if_changed :add_mime_maps do
-      set_mime_maps(new_resource.add_mime_maps, current_resource.add_mime_maps, true, false)
-    end
+  converge_if_changed :add_default_documents do
```
Comment (EasyAsABC123) [inline resources/root.rb]: removed `converge_by` since it doesn't do anything in this use case

File: resources/root.rb [hunk 47]
```diff
@@ -54,41 +54,35 @@
...
+    set_default_documents(new_resource.add_default_documents, current_resource.add_default_documents, true, false)
+  end
+
+  converge_if_changed :add_mime_maps do
+    set_mime_maps(new_resource.add_mime_maps, current_resource.add_mime_maps, true, false)
   end
 end
 
 action :delete do
-  converge_by "Deleted Root Config \"#{new_resource}\"" do
```
Comment (EasyAsABC123) [inline resources/root.rb]: removed `converge_by` since it doesn't do anything in this use case

File: resources/site.rb [hunk 48]
```diff
@@ -167,60 +170,66 @@
...
+    if new_resource.bindings
+      converge_if_changed :bindings do
         cmd = "#{appcmd(node)} set site /site.name:\"#{new_resource.site_name}\""
         cmd << " /bindings:\"#{new_resource.bindings}\""
         Chef::Log.debug(cmd)
         shell_out!(cmd)
-      elsif (new_resource.port || new_resource.host_header || new_resource.protocol) && !new_resource.bindings
+      end
+    elsif new_resource.port || new_resource.host_header || new_resource.protocol
+      converge_if_changed :bindings, :host_header, :protocol do
```
Comment (EasyAsABC123) [inline resources/site.rb]: check if multiple properties changed

File: resources/site.rb [hunk 49]
```diff
@@ -167,60 +170,66 @@
...
 action_class.class_eval do
+  def exists
+    current_resource.site_id ? true : false
+  end
+
   def configure
-    converge_if_changed do
-      if new_resource.bindings
+    if new_resource.bindings
+      converge_if_changed :bindings do
```
Comment (EasyAsABC123) [inline resources/site.rb]: check if `bindings` changed
